### ISSUE TITLE
Spacing off between main page and sidebar

### ISSUE THREAD

**Issue by jacobtfisher** [gavinmn/logseq-luma#30]
Hey there - thanks for the great theme. I love it. I did notice, though, that the spacing seems to be off between the main page and the right sidebar. In the screenshots for the theme, there is a small gap, but when I actually load the theme there is no gap (see picture below), which creates some awkward spacing.

![screenshot_2022-08-03 at 16 58 00@2x](https://user-images.githubusercontent.com/21992882/182719785-1926aa1b-9ca1-46e3-92ad-6fcd4dbfb4cd.png)

I tried commenting out all of the garbage I have in my `custom.css` but it didn't fix the issue. Any suggestions?

**Comment by gavinmn** [comment]
What device are you using and what version of Luma? Are you using the `@import` statement in your CSS or from the marketplace? I've never seen this bug in every version I've released so have you double checked you have _nothing_ in your custom CSS besides Luma?

**Comment by integratorivan** [comment]
I had the same problem when the Craft theme was on. Disable all color schemes and the error goes away :)

**Comment by jacobtfisher** [comment]
I'm on an iMac (Monterey 12.5), and I installed the theme from the marketplace. I also just double-checked that there is nothing in my `custom.css`, and deactivated and reactivated the theme, and it's still occurring. I also tried uninstalling from the marketplace and using the `@import` and am still having the issue. Any other suggestions?

**Comment by gavinmn** [comment]
> I'm on an iMac (Monterey 12.5), and I installed the theme from the marketplace. I also just double-checked that there is nothing in my `custom.css`, and deactivated and reactivated the theme, and it's still occurring. I also tried uninstalling from the marketplace and using the `@import` and am still having the issue. Any other suggestions?

Do you have any other plugins running? Could you try creating a brand new graph and doing nothing but installing the theme?

**Comment by jacobtfisher** [comment]
After going through one by one, I figured out that it's the [Banners Plugin](https://github.com/yoyurec/logseq-banners-plugin) that seems to be causing the issue. Not sure why it changes that right margin, but turning the Banners plugin off and forcing a reload fixes it.
